### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by scattyYT** [ultratype/UltraTypeBot#12]
kaspersky internet security detects a Trojan and deletes the file and does not work pls help

**Comment by ghost** [comment]
Well, disable the security as long as you need to use it, and then enable it again.

**Comment by ultratype** [comment]
Should be fixed, updates will take place in a few minutes. If for some reason your antivirus still falsely detects this extension, do as @moonstarcat524 said and disable it while using UltraType.

**Comment by scattyYT** [comment]
OK
