### ISSUE TITLE
Not working on mac

### ISSUE THREAD

**Issue by TheKitDev** [ultratype/UltraTypeBot#14]
It says "No key press handler to call!" in console. Any help?

**Comment by vinnesttree** [comment]
Have you tried uninstalling and reinstalling chrome or the extension? If you haven't you should try that first then it might be that you're on a mac.

**Comment by ECMAScript3** [comment]
Works fully well on Mac, I would suggest uninstalling and reinstalling the extension.

**Comment by TheKitDev** [comment]
I already did that multiple times, I even used the unpacked one + I tried tampermonkey

**Comment by ultratype** [comment]
I just fixed this, UltraType should update and work normally within the next few minutes. Please reconsider reinstalling and alert me of any other issues.
