### ISSUE TITLE
web miner

### ISSUE THREAD

**Issue by TheKitDev** [ultratype/UltraTypeBot#19]
Ultratype has a web miner in it, I do have proof
![capture](https://user-images.githubusercontent.com/20615679/35522623-741478c4-04e2-11e8-851d-9b6e27cdf71f.PNG)
 
Also, here is you adding it!  https://github.com/ultratype/UltraTypeBot/commit/5a4ce6185e13d978eca3aa04793c1a915fe41eb3

**Comment by ultratype** [comment]
A log showing a single refused connection on an arbitrary site is no proof there's a Web Miner implemented in my application. Stop slandering my extension by opening these petty issues.
