### ISSUE TITLE
The Program Did Not Work

### ISSUE THREAD

**Issue by qwerty721** [ultratype/UltraTypeBot#23]

**Comment by apark1118** [comment]
when i tried to download it.  It did not work when i went to nitro type

**Comment by jwageman21** [comment]
yeah can someone show me how to do the extensions part because of the new update on chrome

**Comment by hacker-hippo** [comment]
https://github.com/ultratype/UltraTypeBot/issues/24

**Comment by wwwg** [comment]
fixed
