### ISSUE TITLE
Does not work it goes black

### ISSUE THREAD

**Issue by jnene77** [ultratype/UltraTypeBot#24]
When I load up the thing it just goes black and I cant see the race

**Comment by lexus990** [comment]
same here, i can't play the damn thing!

**Comment by ZST1** [comment]
ikr, the thing goes black and stays there

**Comment by hacker-hippo** [comment]
Did you download through .zip or Chrome extension? If you downloaded with chrome extension, make sure you have BOTH extensions installed.
