### ISSUE TITLE
Stops after The first word

### ISSUE THREAD

**Issue by johnathan223232323** [ultratype/UltraTypeBot#25]
Seems to stop right after the first work every time. I have uninstalled and reinstalled about 3 times now. And it still does not work

**Comment by johnathan223232323** [comment]
It's not just the 12th letter it usually stops after the first word. Or stops mid second word.

**Comment by johnathan223232323** [comment]
I'm focused on the tab, but it stops. I have viewed other issues and nobody is having the same problem I am.

**Comment by ECMAScript3** [comment]
Can you post any console output? Are you using the extension or the tampermonkey script? Are you using the menu properly? What browser are you using?

If you can find out a way to reproduce it I can look into fixing it.

**Comment by johnathan223232323** [comment]
Tampermonkey, watched 2 videos about it, chrome.

**Comment by hacker-hippo** [comment]
If you think you might be banned, clear cookies, disable Tampermoney script, and reinable Tampermonkey scripts. That should solve any issues.

**Comment by johnathan223232323** [comment]
I uninstalled and reinstalled tamper monkey and cleared cookies, and is still not working.

**Comment by jm02394** [comment]
I am having the same issue, and that also didn't work.

**Comment by typazo** [comment]
Same for me, I have a gif [EDIT: formerly said video] of it here (I use tampermonkey beta and and full release, neither worked.)

![nitro-type-bot-not-work](https://user-images.githubusercontent.com/43455506/45850199-35cd5200-bd03-11e8-9ecb-d1a4e42c2d7a.gif)


Help!!

**Comment by Kazazzy** [comment]
Yeah, it isn't working for me either.

EDIT: I deleted my cookies and I was fine.

EDIT 2: Nope. Now that I've logged into an account, it's bugged. Even if I clear my cookies, log in, and race, it happens. I'm really confused.

**Comment by HEWFISHISME** [comment]
Why I use the script but it didn't work

**Comment by HEWFISHISME** [comment]
can someone fix for me? pls

**Comment by matthewpi72637** [comment]
its happening to me too its so dumb
