### ISSUE TITLE
{This Project has been Discontinued by the Owner of this Repo until Further Notice}

### ISSUE THREAD

**Issue by VuBrian22** [ultratype/UltraTypeBot#31]

**Comment by ECMAScript3** [comment]
Yeah it was fun while it lasted but we eventually got bored of fighting the developers. It is unlikely we will ever update this code again

**Comment by VuBrian22** [comment]
Agreed. It was a fun ride. I'm sad to see it go. :(

**Comment by aahanispog** [comment]
I never got to try it :(

**Comment by phyouthcenter1** [comment]
You can still use it. Discontinued means stopped being produced (worked on)

**Comment by wwwg** [comment]
as of today, i will be working on this project again. i apologize for the inconvenience and hopefully itll be working within the next week or so.
