### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by Kazazzy** [ultratype/UltraTypeBot#5]
Repost, accidentally posted this on the UltraBot++ code instead of here.

I have used both the Tampermonkey and using the developer tool extension thing and both of them have resulted in my computer lagging multiple seconds and slowing to a crawl. I looked at my task manager and realized that a certain software on Google Chrome was causing it. Whenever I pressed "End Task" on the task that was causing 100% CPU usage, the usage turns back into 2% or so and I get a notification that the extension has crashed.
I want to keep using this program, but I fear for my CPU because it doesn't seem to be healthy and I don't want it to not live as long. I have an Intel i5-6500 CPU.
CPU specs: https://goo.gl/3c3Hxi

**Comment by Kr4ken-9** [comment]
I get about 10% CPU usage with an i5-4590. How does this compare to UltraBot++ performance, or have you compared?

**Comment by Kazazzy** [comment]
I have tried UltraBot++ and it hasn't worked out... but I have been using the Tampermonkey version for months and it worked fine (didn't completely lag out my computer) up until this Monday.

**Comment by ultratype** [comment]
I republished the extension on the webstore, readd the extension and your problem should be fixed.
