### ISSUE TITLE
Chrome extension link doesn't work

### ISSUE THREAD

**Issue by ifvictr** [ultratype/UltraTypeBot#7]
Every time I try to use the link, I receive a 404. Did it get removed from the store?

**Comment by vinnesttree** [comment]
The reason this is happening is that google took the extension down. They always do this to Ultratype.

**Comment by ghost** [comment]
Use the tampermonkey script.

**Comment by ultratype** [comment]
Republished the extension on the webstore today, try again.

**Comment by ghost** [comment]
Can you make a mobile app for this?

**Comment by ultratype** [comment]
no
