### ISSUE TITLE
Leveling up and money not going up

### ISSUE THREAD

**Issue by vinnesttree** [ultratype/UltraTypeBot#8]
I've been having this for a while now, but when ever I let it run it keeps leveling up then saying that I leveled up to the level I was previously at. Is this a IP ban or something else. Please help me.

**Comment by ghost** [comment]
Actually, I know this is an issue because Nitrotype made a patch that if It detects that you are using a bot then just resets.

**Comment by scattyYT** [comment]
hi i have the same prblem here can some one please help me ASAP

**Comment by ultratype** [comment]
Fixed! I'm releasing an update to the Chrome WebStore now. UltraType is no longer detectable.

**Comment by scattyYT** [comment]
is it fixed like is it now fixed
did you update it ???

**Comment by ultratype** [comment]
Yes.
